export const sampleAssignments = [
  {
    id: 1,
    title: "양파랜드 디오라마",
    startDate: 1715147728848,
    dueDate: 1718157728848,
    curriculum: "식물 키우기",
    submissions: 3,
    classSize: 10,
    details: "양파랜드 디오라마를 만듭니다.",
    isArchived: false,
    submitters: ["김철수", "박순희", "최영희"],
  },
  {
    id: 2,
    title: "양파 식물일기 작성",
    startDate: 1717157728848,
    dueDate: 1718157728848,
    curriculum: "식물 키우기",
    submissions: 9,
    classSize: 10,
    details: "한달 동안 양파가 자라는 과정을 그림일기로 작성합니다.",
    isArchived: false,
    submitters: ["김철수", "박순희", "최영희", "홍길동", "고양이", "강아지", "김제자", "차대리", "이과장"],
  },
  {
    id: 3,
    title: "[해커수학 미적분II] 문제집 풀이",
    startDate: 1708157728848,
    dueDate: 1718157728848,
    curriculum: "수학: 미적분",
    submissions: 5,
    classSize: 5,
    details: "해커수학 미적분 II 문제집 챕터 4 섹션 2부터 5까지 읽고 연습문제를 풀어요.",
    isArchived: false,
    submitters: ["김철수", "박순희", "최영희", "홍길동", "고양이"],
  },
  {
    id: 4,
    title: "영문 글쓰기 연습 2",
    startDate: 1722157728848,
    dueDate: 1739157728848,
    curriculum: "영어 - 해외여행",
    submissions: 6,
    classSize: 8,
    details:
      "해외여행을 가서 겪었던 어려운 일에 대해 말해주세요. 소지품을 잃어버리거나 일정이 계획한 대로 풀리지 않은 경험이 있었는지 생각해봅니다. 이번 챕터에서 배웠던 단어들을 조합해 200자 이상으로 작성해봅니다.",
    isArchived: false,
    submitters: ["김철수", "박순희", "최영희", "홍길동", "고양이", "강아지"],
  },
  {
    id: 5,
    title: "영문 글쓰기 연습 3",
    startDate: 1740167728848,
    dueDate: 1744157728848,
    curriculum: "영어 - 학교생활",
    submissions: 4,
    classSize: 8,
    details: "학교생활을 할 때 지켜야 할 중요한 수칙들이 무엇이 있을까요?",
    isArchived: false,
    submitters: ["박순희", "최영희", "홍길동", "고양이"],
  },
];

export const sampleCurriculums = [
  {
    id: 1,
    name: "식물 키우기",
    goal: "식물을 직접 키워보면서 식물의 생태에 대해 공부합니다.",
    chapters: [
      { number: 1, topic: "상추" },
      { number: 2, topic: "양파" },
      { number: 3, topic: "배추" },
    ],
    totalChapters: 3,
    currentChapter: 2,
    classSize: 10,
    students: ["김철수", "박순희", "최영희", "홍길동", "고양이", "강아지", "김제자", "차대리", "이과장", "주차장"],
  },
  {
    id: 2,
    name: "수학: 미적분",
    goal: "미적분 중급 과정을 배웁니다.",
    chapters: [
      { number: 1, topic: "중급 미적분 (상)" },
      { number: 2, topic: "중급 미적분 (하)" },
    ],
    totalChapters: 2,
    currentChapter: 1,
    classSize: 5,
    students: ["김철수", "박순희", "최영희", "홍길동", "고양이"],
  },
  {
    id: 3,
    name: "영어 - 해외여행",
    goal: "해외여행을 주제로 프리토킹과 작문을 통해 영어를 배웁니다.",
    chapters: [
      { number: 1, topic: "가고 싶은 여행지" },
      { number: 2, topic: "여행 준비 과정" },
      { number: 3, topic: "어려운 경험" },
      { number: 4, topic: "새로운 경험" },
      { number: 5, topic: "여행지 소개" },
    ],
    totalChapters: 5,
    currentChapter: 3,
    classSize: 8,
    students: ["김철수", "박순희", "최영희", "홍길동", "고양이", "강아지", "주차장", "김제자"],
  },
  {
    id: 4,
    name: "영어 - 학교생활",
    goal: "학교생활을 주제로 프리토킹과 작문을 통해 영어를 배웁니다.",
    chapters: [
      { number: 1, topic: "학교와 규칙" },
      { number: 2, topic: "학우와 소통" },
      { number: 3, topic: "학교 시설" },
      { number: 4, topic: "교내 행사" },
    ],
    totalChapters: 4,
    currentChapter: 1,
    classSize: 8,
    students: ["김철수", "박순희", "최영희", "홍길동", "고양이", "강아지", "주차장", "김제자"],
  },
];
